### PR TITLE
Blockquote Style

### LINKED ISSUE #29: Blockquote Formatting
Currently blockquotes do not indent and have larger text than the rest of the page.

### PR DESCRIPTION
**Pull request by Bosterm**
Resolves #29.

This adds style rules for blockquotes (<blockquote></blockquote>) and restores margins previously taken away by bootstrap (the left and right margins only appear on desktop).

By default, blockquote text is also larger (22 pixels) and has a left border to distinguish it from the rest of the text. It is possible to remove the left border by adding the class "plain" to the blockquote element, and users can make the text the same size as regular paragraphs by adding the "regular-text" class.

Let me know if this css class solution is okay or not. It is a bit more advanced and requires some documentation, but I figured most people aren't likely to use a blockquote element, and those that do are more likely to know about CSS classes. An alternative could be to add the border and larger text through css classes and the default does not have these styles, but I thought most people would preer the extra style.

### CODE REVIEW

**Comment by alexdryden** [comment]
Thanks for working on the @Bosterm ! There was recently another user request related to Block Quotes, and it looks like I made it into a duplicate issue #39. I think it would be best if we could limit as much complexity as possible and expose all options through the WYSIWYG, if possible, especially given the amount of documentation that users already have to absorb to use the theme successfully.  

The style looks great, but lets see if there is a way integrate the font size and left border into the existing controls.

**Comment by Bosterm** [comment]
Good point about the WSIWYG editor having the blockquote button. In the short term, would it be okay to keep this issue at just restoring the margins, since that's a default browser style thing that boostrap removed? The border and font-size can then go with the WSIWYG issue.

If so, I'll go ahead and update the CSS accordingly.

**Comment by alexdryden** [comment]
Sure thing.

**Comment by alexdryden** [comment]
I'm going to leave the pull request open for now, but I'll push this out to production. I suspect that there are additional plugins for the CKEditor that can accomplish the effects you described in your initial pull request, and then we can just include them as dependencies.

**Pull request merged**
