### PR TITLE
Reposition and Hide Universal Viewer with Theme Config

### LINKED ISSUE #18: Make metadata collapsible
This is a workaround for the issue where the metadata precedes the image on item show pages. Make the metadata in a collapsible section that loads closed.

### PR DESCRIPTION
**Pull request by Bosterm**
This closes #18. Using JS, it moves the universal viewer to the top of the pages on which it appears, and users can use the theme config to hide the universal viewer on particular pages (item show, item browse, item set browse).

### CODE REVIEW

**Comment by alexdryden** [comment]
This is looking good. All my dev environments are on Omeka 3 now, so I'm going to test this out on the sandbox and will push to production if everything checks out. I think I'm going to have to take out the loading GIF to meet accessibility standards about moving GIFs, but we'll see.

**Comment by alexdryden** [comment]
This looks really good. One thing I'll like to tweak is the controls for UV placement on various pages. I think the release should, in this case, have default settings that make it so existing users experience zero side effects. 

To that end, I think instead of toggling the UV on/off in the theme config, there should be a three choice drop down: top (the zero side effect default option), bottom, and off. 

I've not yet seen the spinning/waiting GIF in action--I think I may need to slow down my connection speed to get it to show up, or am I misunderstanding how that feature is activated?

**Comment by Bosterm** [comment]
That sounds good, I can make that adjustment to add the third option for the theme config. That way it wouldn't conflict with the 'block disposition' module.

I think the spinning gif is most common to happen if images load slowly. This happens on my site since my image server is set up slightly differently. See https://benostermeier.com/omekas/s/site-one/item/1422 for an example.

**Comment by Bosterm** [comment]
Okay this should work now.

**Comment by alexdryden** [comment]
Awesome, thanks! I think I would rather the loading signal be textual rather than a moving GIF. But I see now you were reproducing the way the viewer behaves natively. Because it is a separate issue from the viewer placement I think we can deal with in its own issue.

**Pull request merged**
