### PR TITLE
Fix Centered Bottom Margin and Banner Image Size

### LINKED ISSUE #14: Minor CSS Adjustments (embedded video margin and banner size)
There are two unrelated minor CSS errors/adjustments I've discovered that need fixing:

1. Embedded media that uses video instead of an image also needs a bottom margin between it and the caption.
2. I'd like to set the banner image at the top to 'contain' instead of 'cover' on desktop screens, since a lot of the image ends up going missing on larger resolutions. This is less of an issue with the default image I selected, but I noticed it was a problem with custom images I was trying to set for RBML.

Since both of these are one commit each, I thought it would be easier to just do it as one issue and branch.

### PR DESCRIPTION
**Pull request by Bosterm**
This resolves #14.

### CODE REVIEW

**Comment by Bosterm** [comment]
I made a few more adjustments today to make the banner image look a bit banner at different desktop sizes, using the top 10 desktop resolutions used in the United States (https://gs.statcounter.com/screen-resolution-stats/desktop/united-states-of-america)

**Comment by alexdryden** [comment]
@Bosterm I think this looks great for the landing page, but it makes navigating through the exhibit a little more difficult because almost all of the content ends up below the fold. 

I looked into it a little bit and I while I still don't see an obvious way to get a different banner for each exhibit, I think we can at least do a banner for the homepage and a banner for exhibit pages by simply adding an additional section in the theme config for a homepage banner and then testing in the view to see if the current page is set to the homepage. Then we would just need to add a class to the banner on the homepage and refactor some of these changes to only apply to something like `.banner.homepage` so there is a little more focus on the content on exhibit pages.

There is also talk on the dev forum about adding some more dynamic capabilities to the theme.ini file, so if that gets implemented we would have a path to get different banners per exhibit, potentially.

**Comment by Bosterm** [comment]
Yeah I agree, this ended up being a bit larger than expected. For now we could add a feature to make the banner a lot shorter on non-homepages. Unfortunately I haven't had as much free time the last couple of weeks due to the semester wrapping up, but I should be more available pretty soon.

Also doesn't help that my personal website instance of Omeka S decided to break unexpectedly, and I haven't had time to fix it.

**Comment by alexdryden** [comment]
Yeah, same with being busy. And after next week I'm going to be out for a
week or two while we move and get settled. I pushed this update to the
sandbox and production. Do you think that we should back out till we can
address the banner on content pages, or do you think it is good enough for
now?

**Pull request merged**
